version: '3.9'

services:
  db:
    image: postgres:18-alpine
    container_name: my_postgres_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    privileged: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "80:80"
