events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name app1.local app2.local;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name app1.local;

        ssl_certificate_key /etc/nginx/certs/app1_key.pem;
        ssl_certificate     /etc/nginx/certs/app1_cert.pem;

        location /static/ {
            alias /var/www/static/app1/;
        }

        location / {
            proxy_pass http://app1:8000;
            include /etc/nginx/proxy_params.conf;
        }
    }

    server {
        listen 443 ssl;
        server_name app2.local;

        ssl_certificate_key /etc/nginx/certs/app2_key.pem;
        ssl_certificate     /etc/nginx/certs/app2_cert.pem;

        location /static/ {
            alias /var/www/static/app2/;
        }

        location / {
            proxy_pass http://app2:8000;
            include /etc/nginx/proxy_params.conf;
        }
    }
}
